kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: team-X-mails
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
    receivers:
    - name: 'team-X-mails'
      email_configs:
        - to: 'akarypbayeva@confluent.io'
          html: '{{ template "email.default.html" . }}'
          # text: 'sample text for email: {{ template "__subject" . }}'
          # text: '{{ template "email.default.text" . }}'