apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
              "access":"proxy",
              "editable": true,
              "name": "Prometheus",
              "orgId": 1,
              "type": "prometheus",
              "url": "http://10.226.97.72:9090",
              "version": 1
            }
        ]
    }